### ISSUE TITLE
Error on accuracy randomize in `TestUtil`

### ISSUE THREAD

**Issue by HelloYeew** [HelloYeew/maisim#73]
```csharp
[runtime] 2022-05-22 16:57:43 [error]: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'accuracy')
[runtime] 2022-05-22 16:57:43 [error]: at maisim.Game.Scores.ScoreProcessor.CalculateRank(Single accuracy) in C:\Users\HelloYeew\RiderProjects\maisim\maisim\maisim.Game\Scores\ScoreProcessor.cs:line 82
[runtime] 2022-05-22 16:57:43 [error]: at maisim.Game.Utils.TestUtil.CreateMockScore(Beatmap beatmap) in C:\Users\HelloYeew\RiderProjects\maisim\maisim\maisim.Game\Utils\TestUtil.cs:line 134
[runtime] 2022-05-22 16:57:43 [error]: at maisim.Game.Utils.TrackTestFixture..ctor(String trackTitle) in C:\Users\HelloYeew\RiderProjects\maisim\maisim\maisim.Game\Utils\TestUtil.cs:line 172
[runtime] 2022-05-22 16:57:43 [error]: at maisim.Game.Tests.Visual.Component.TestSceneTrackCardFocusedManyStyle..ctor() in C:\Users\HelloYeew\RiderProjects\maisim\maisim\maisim.Game.Tests\Visual\Component\Te
stSceneTrackCardFocusedManyStyle.cs:line 73
[runtime] 2022-05-22 16:57:43 [error]: at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

This maybe due the randomization in `TestUtil`. It's random occured but need to be fix this.

**Comment by pontakornth** [comment]
I think the error is from `CalculateRank` function.

```csharp
            if (accuracy >= 100.5f)
            {
                return ScoreRank.SSSPlus;
            }

            if (accuracy >= 100 && accuracy <= 100.49f)
            {
                return ScoreRank.SSS;
            }
```
If the accuracy is `100.492f`, it won't fit in any condition. The solution is to have the same bound.

```csharp
            if (accuracy >= 100.5f)
            {
                return ScoreRank.SSSPlus;
            }

            if (accuracy >= 100 && accuracy < 100.5f)
            {
                return ScoreRank.SSS;
            }
```

The alternative would be using downward if-else condition instead.

```csharp
            if (accuracy >= 100.5f)
            {
                return ScoreRank.SSSPlus;
            }

            else if (accuracy >= 100)
            {
                // If this condition is reached, accuracy is lower than 100.5 .
                return ScoreRank.SSS;
            }
```
